services:
  backend:
    build:
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./backend:/app/backend:z
      - /app/backend/.venv
    ports:
      - "8000:8000"
    environment:
      ENVIRONMENT: development
    command:
      - uvicorn
      - src.api:api.app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - --reload

  bot:
    build:
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./bot:/app/bot:z
      - ./backend:/app/backend:z
    environment:
      ENVIRONMENT: development
    command:
      - python
      - -m
      - app.main

  db:
    ports:
      - "5433:5432"

  redis:
    ports:
      - "6379:6379"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  internal:
    internal: false