"""empty message

Revision ID: 24935868b4fa
Revises: a41f4945ff83
Create Date: 2026-07-03 09:57:03.356103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24935868b4fa'
down_revision: Union[str, Sequence[str], None] = 'a41f4945ff83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stats', 'strenght', new_column_name='strength')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stats', 'strength', new_column_name='strenght')
    # ### end Alembic commands ###
